#!/bin/sh

set -x

INSTALL_PKGS="go-toolset-1.11.5"
#OPERATOR_VERSION="0.2.1"
OPERATOR_PATH=/usr/local/bin/infinispan-operator

yum -y install ${INSTALL_PKGS}

REPO=infinispan-operator
GHORG=github.com/infinispan
GHFULL=${GHORG}/${REPO}
GOPATH=$(go env GOPATH)
go version

mkdir -p ${GOPATH}/src/${GHFULL}
tar xfz /tmp/artifacts/operator.tar.gz --strip-components=1 -C ${GOPATH}/src/${GHFULL}
cd ${GOPATH}/src/${GHFULL} && pwd

go generate ./...
go vet ./...
go test ./...
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o ${OPERATOR_PATH} github.com/infinispan/infinispan-operator/cmd/manager
if [[ ! -f ${OPERATOR_PATH} ]] ; then
    echo "${OPERATOR_PATH} does not exist, aborting."
    exit 1
fi

mv build/bin/* /usr/local/bin/

mkdir -p operator-manifests
tar xfz /tmp/artifacts/manifests.tar.gz --strip-components=1 -C operator-manifests
find operator-manifests/upstream-community-operators/infinispan \
    -name '*.yaml' \
    -exec "./format-yaml.py" {} \;

mv operator-manifests/* /manifests
#mv deploy/crds/kieapp.crd.yaml /manifests
#/usr/local/bin/user_setup

yum -y autoremove ${INSTALL_PKGS}
yum -y update-minimal --setopt=tsflags=nodocs --security --sec-severity=Important --sec-severity=Critical
yum clean all
rm -rf /var/cache/yum ${GOPATH}
